version: "3"
services:
  web:
    container_name: eakigbo_website
    env_file: .env
    build: .
    command: npm run dev
    restart: always
    networks:
      - internal
      - default
    ports:
      - ${EXPOSED_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    volumes:
      - .:/usr/app

networks:
  internal:
    driver: bridge
    internal: true
  default:
    external:
      name: ${EXTERNAL_NETWORK}
