version: "3"
services:
  web:
    container_name: eakigbo_website
    env_file: .env
    build: .
    command: npm run deploy
    restart: always
    networks:
      - internal
      - default
    ports:
      - ${EXPOSED_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      VIRTUAL_PORT: ${PORT}
      VIRTUAL_HOST: ${DOMAIN}, www.${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}, www.${DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_TEST: ${LETSENCRYPT_TEST}
    volumes:
      - .:/usr/app

networks:
  internal:
    driver: bridge
    internal: true
  default:
    external:
      name: ${EXTERNAL_NETWORK}
